In [1]:
import nltk
# nltk.download('averaged_perceptron_tagger_eng')
# nltk.download('punt_tab')

import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import re
from pathlib import Path
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from tqdm import tqdm
import contractions
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk import pos_tag

In [2]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import wordnet
# Initialize stemmer/lemmatizer (run once)
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Step 1: Load the speeches

In [45]:
#probando

In [3]:
base_path_alvaro = Path(r"C:\Users\Alvaro Millan Ruiz\OneDrive\Escritorio\BDS\Block_5\NLP\Project\TXT")
base_path_gilda = "/Users/szonjapike/Desktop/BDS/Block_5/NLP/TXT/"

base_path = base_path_gilda # change according to user

In [4]:
dataset_path_alvaro = r"C:\Users\Alvaro Millan Ruiz\OneDrive\Escritorio\BDS\Block_5\NLP\Project"
dataset_path_gilda = "/Users/szonjapike/Desktop/BDS/Block_5/NLP/Project/"

dataset_path = dataset_path_gilda # change according to user

In [5]:
# Upload the df_raw speech that we obtained in the notebook "2. Load Speeches"
df_raw = pd.read_csv(dataset_path + "UN_Speeches_raw.csv") 

# Choose from 1990 onwards
df_raw_1990 = df_raw[df_raw['Year'] >= 1990]
df_raw_1990

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens
4430,45,1990,NZL,"﻿\nI should like to congratulate you, Sir, on ...",145,3512
4431,45,1990,EGY,"﻿First of all, I would like to extend may dele...",76,2532
4432,45,1990,CSK,"﻿Mr. President, allow me to congratulate you o...",157,4328
4433,45,1990,CPV,﻿I should like to begin by offering Mr. de Mar...,71,2432
4434,45,1990,UGA,"﻿In 1967, I had the privilege of addressing th...",132,3508
...,...,...,...,...,...,...
10947,79,2024,CIV,Mr President of the 79th Session of the United...,41,1206
10948,79,2024,HND,"Madam President of this General Assembly, \nM...",54,1367
10949,79,2024,MKD,Distinguished President of the United Nations ...,101,2804
10950,79,2024,KOR,"Mr. President,\nMr. Secretary-General,\nDistin...",31,821
10951,79,2024,SGP,"Mdm President, Your Excellencies \n \n \n1 I...",100,2208

In [6]:
# Load the income labels

label_income_1990 = pd.read_csv(dataset_path + "label_world_bank_1990.csv") 
label_income_1990

                     Entity ISO-Code  Year  Income Level
0               Afghanistan      AFG  1990           1.0
1               Afghanistan      AFG  1991           1.0
2               Afghanistan      AFG  1992           1.0
3               Afghanistan      AFG  1993           1.0
4               Afghanistan      AFG  1994           1.0
...                     ...      ...   ...           ...
7325  Virgin Islands (U.S.)      VIR  2024           4.0
7326     West Bank and Gaza      PSE  2024           2.0
7327            Yemen, Rep.      YEM  2024           1.0
7328                 Zambia      ZMB  2024           2.0
7329               Zimbabwe      ZWE  2024           2.0

[7330 rows x 4 columns]

In [7]:
def add_income_level(speeches_df, income_df):
    # merge on ISO-Code and Year
    merged = speeches_df.merge(
        income_df[['ISO-Code', 'Year', 'Income Level']],
        how='left',
        on=['ISO-Code', 'Year']
    )
    
    # fill missing income levels with 0
    merged['Income Level'] = merged['Income Level'].fillna(0).astype(int)
    
    return merged

df_combined = add_income_level(df_raw_1990, label_income_1990)
df_combined

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens,Income Level
0,45,1990,NZL,"﻿\nI should like to congratulate you, Sir, on ...",145,3512,4
1,45,1990,EGY,"﻿First of all, I would like to extend may dele...",76,2532,1
2,45,1990,CSK,"﻿Mr. President, allow me to congratulate you o...",157,4328,0
3,45,1990,CPV,﻿I should like to begin by offering Mr. de Mar...,71,2432,2
4,45,1990,UGA,"﻿In 1967, I had the privilege of addressing th...",132,3508,1
...,...,...,...,...,...,...,...
6517,79,2024,CIV,Mr President of the 79th Session of the United...,41,1206,2
6518,79,2024,HND,"Madam President of this General Assembly, \nM...",54,1367,2
6519,79,2024,MKD,Distinguished President of the United Nations ...,101,2804,3
6520,79,2024,KOR,"Mr. President,\nMr. Secretary-General,\nDistin...",31,821,4
6521,79,2024,SGP,"Mdm President, Your Excellencies \n \n \n1 I...",100,2208,4

In [8]:
final_df = df_combined[df_combined['Income Level'] != 0]
final_df   # maybe save this for later, would be nice

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens,Income Level
0,45,1990,NZL,"﻿\nI should like to congratulate you, Sir, on ...",145,3512,4
1,45,1990,EGY,"﻿First of all, I would like to extend may dele...",76,2532,1
3,45,1990,CPV,﻿I should like to begin by offering Mr. de Mar...,71,2432,2
4,45,1990,UGA,"﻿In 1967, I had the privilege of addressing th...",132,3508,1
5,45,1990,NLD,"﻿\nMay I, first of all, extend to Mr. de Marco...",167,4134,4
...,...,...,...,...,...,...,...
6517,79,2024,CIV,Mr President of the 79th Session of the United...,41,1206,2
6518,79,2024,HND,"Madam President of this General Assembly, \nM...",54,1367,2
6519,79,2024,MKD,Distinguished President of the United Nations ...,101,2804,3
6520,79,2024,KOR,"Mr. President,\nMr. Secretary-General,\nDistin...",31,821,4
6521,79,2024,SGP,"Mdm President, Your Excellencies \n \n \n1 I...",100,2208,4

In [21]:
final_df_before_cleaning_keywords = final_df.copy()
final_df_before_cleaning_keywords.to_csv("/Users/szonjapike/Desktop/BDS/Block_5/NLP/Project/final_df_before_cleaning_keywords.csv", index=False, encoding='utf-8')

# Step 2: Cleaning Functions

In [9]:
def take_out_mentions_to_the_president(text):
    """Remove introductory phrases addressing the president or other dignitaries from text.
    Args:
        text (str): The input text to process    
    Returns:
        str: The text with introductory address phrases removed, or original text if none found
    """
    
    # Split into sentences (simple regex)
    # The regex looks for sentence-ending punctuation followed by whitespace
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    
    # Get first 4 sentences as search area - addresses are typically at the beginning
    search_area = ' '.join(sentences[:2]).lower()
    
    # Phrases to search for (lowercase)
    # We look for various forms of presidential/dignitary addresses
    # Store the index where each phrase is found (-1 if not found)
    possible_starts = [
        search_area.lower().find("mr. president"),  # Formal address with period
        search_area.lower().find("mr president"),   # Formal address without period
        search_area.lower().find("ladies and gentlemen"),  # Common formal address
        search_area.lower().find("your excellency"),  # Covers "your excellence" and "your excellency"
        search_area.lower().find("your excellence"),  # Covers "your excellence" and "your excellency"
        search_area.lower().find("your majesties"),  # 
        search_area.lower().find("your majesties"),  # 
        search_area.lower().find("president of the general assembly"),
        search_area.lower().find("excellencies"),     # Plural form of address
        search_area.lower().find("esteemed president"),  # Honorific address
        search_area.lower().find("distinguished delegates"),  # Assembly address
        search_area.lower().find("allah"),  # Address to members of an assembly
    ]
    
    # Filter out phrases that weren't found (-1) and keep only valid indices
    starts = [start for start in possible_starts if start != -1]
    
    # Get the latest occurrence of any address phrase
    start = max(starts) if len(starts) > 0 else -1
    
    if start == -1:
        # No address phrases found - log this and return full text
        # print(f"Could not find probable start in the text of {url}")
        start = 0
    
    # Return text starting from after the address phrase
    return text[start:]

In [10]:
def simple_clean(text):
    """Cleans text by removing common formatting artifacts from PDF conversions and UN document patterns.
    
    Args:
        text (str): Input text to be cleaned
        
    Returns:
        str: Cleaned text with unwanted patterns removed
    """
    
    # Convert to lowercase for consistent processing 
    text = text.lower()
  
    # 1: Remove UN document reference numbers (e.g. "20/26 15-29876")
    text = re.sub(r'\b\d{1,4}\s*/\s*\d{1,4}\s+\d{2,4}-\d{4,8}\b', ' ', text)
    
    # 2: Remove UN meeting record references (e.g. "A/70/PV.24")
    text = re.sub(r'\b[a-z]\s*/\s*\d+\s*/pv\s*\.\s*\d+\b', ' ', text, flags=re.IGNORECASE)
    
    # 3: Remove dates in DD/MM/YYYY format (e.g. "31/12/2023")
    text = re.sub(r'\d{2}\/\d{2}\/\d{4}', '', text) 
  
    # 4: Remove form feed characters (often from PDF conversion)
    text = re.sub(r'\x0c', '', text) 
  
    # 5: Remove parenthetical document references (e.g. "(A/70/123)" or "(A/70/123, annex)")
    text = re.sub(r'\(\s*[a-z]\s*/\s*\d+\s*/\s*\d+\s*(?:,\s*annex)?\s*\)', '', text, flags=re.IGNORECASE)
    
    # 6: Remove standalone line numbers/page numbers (e.g. "42" on its own line)
    text = re.sub(r'^\s*\d+\s*$\n?', '', text, flags=re.MULTILINE)
    
    # 7: Normalize newlines - replace all with single spaces
    text = re.sub(r'\n', ' ', text, flags=re.MULTILINE)

    # 8: Remove numbered list prefixes (e.g. "1.    Some text")
    text = re.sub(r'\d+\.\t', '', text)

    # 9: Remove Unicode BOM (Byte Order Mark) character if present
    text = text.replace('\ufeff', '')
    
    # 10: Normalize whitespace - collapse multiple spaces into one and trim
    text = re.sub(r'\s+', ' ', text).strip()

    # 11. Remove standalone hyphens
    text = re.sub(r'\s*-(?!\w)(?<!\w)-*\s*', ' ', text)

    # 12: Remove punctuations
    text = text.replace('—', '').replace(',', '').replace(':', '').replace('’', '').replace('“', '').replace("”", '').replace(";", '').replace("''", '')
    
    # 12: Remove words/numbers between parenthesis
    text = re.sub(r'\([^)]*\)', '', text)
        
    return text

In [11]:
def remove_stopwords(text):
    """Remove common stopwords from text"""
    stop_words = set(stopwords.words('english'))
    words = word_tokenize(text)
    filtered_words = [word for word in words 
                 if word.lower() not in stop_words and len(word) > 2]
    return ' '.join(filtered_words)

In [12]:
def remove_punctuations(text):
    return text.replace('.', '').replace('?', '').replace('!', '')

In [13]:
def stem_text(text):
    words = word_tokenize(text)
    stemmed_words = [stemmer.stem(word) for word in words]
    return ' '.join(stemmed_words)


def get_wordnet_pos(word):
    """Map POS tag to first character used by WordNetLemmatizer"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {
        "J": wordnet.ADJ,
        "N": wordnet.NOUN,
        "V": wordnet.VERB,
        "R": wordnet.ADV
    }
    return tag_dict.get(tag, wordnet.NOUN)


def lem_text(text):
    words = word_tokenize(text)
    stemmed_words = [lemmatizer.lemmatize(word, get_wordnet_pos(word)) for word in words]
    return ' '.join(stemmed_words)

In [14]:
def clean_speeches(text, use_simple_clean=True, disregard_mentions_to_president=True, Remove_Stopwords = False, expand=False, Remove_Punctuations = False, 
                        lemma=False):
    """Load a text file and apply cleaning operations. 
    Args:
        text: Original text
        use_simple_clean (bool): Whether to apply basic text cleaning
        disregard_mentions_to_president (bool): Whether to remove mentions to the president
        Returns:
        str: Cleaned text from the file"""
    
    if expand: 
        text = contractions.fix(text) 

    # Apply basic text cleaning if the flag is set
    if use_simple_clean:
        text = simple_clean(text)  # Assumes simple_clean is a custom function defined elsewhere

    # Remove mentions to the president if the flag is set
    if disregard_mentions_to_president:
        text = take_out_mentions_to_the_president(text)  # Also assumes this function is defined elsewhere
    
    # Remove Stopwrods
    if Remove_Stopwords:
        text = remove_stopwords(text)

    # Remove Punctuations
    if Remove_Punctuations:
        text = remove_punctuations(text)

    # Lemmatize everything
    if lemma:
        text = lem_text(text)

    # Replace only spaces/tabs induced from the stopwords
    text = re.sub(r'[ \t]+', ' ', text)

    # Return the cleaned (or original) text
    return text

In [15]:
final_df

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens,Income Level
0,45,1990,NZL,"﻿\nI should like to congratulate you, Sir, on ...",145,3512,4
1,45,1990,EGY,"﻿First of all, I would like to extend may dele...",76,2532,1
3,45,1990,CPV,﻿I should like to begin by offering Mr. de Mar...,71,2432,2
4,45,1990,UGA,"﻿In 1967, I had the privilege of addressing th...",132,3508,1
5,45,1990,NLD,"﻿\nMay I, first of all, extend to Mr. de Marco...",167,4134,4
...,...,...,...,...,...,...,...
6517,79,2024,CIV,Mr President of the 79th Session of the United...,41,1206,2
6518,79,2024,HND,"Madam President of this General Assembly, \nM...",54,1367,2
6519,79,2024,MKD,Distinguished President of the United Nations ...,101,2804,3
6520,79,2024,KOR,"Mr. President,\nMr. Secretary-General,\nDistin...",31,821,4
6521,79,2024,SGP,"Mdm President, Your Excellencies \n \n \n1 I...",100,2208,4

In [16]:
nltk.download('wordnet')
tqdm.pandas()  # Enable pandas integration

# final_df_2010_2017 = final_df[(final_df['Year'] >= 2010) & (final_df['Year'] <= 2017)]

final_df['speeches_for_keyword_search'] = final_df['Speech'].progress_apply(
    lambda x: clean_speeches(
        x, 
        expand=True,
        use_simple_clean=True, 
        disregard_mentions_to_president=True, 
        Remove_Stopwords=False,        # No removal of stopwords
        Remove_Punctuations= False,      # No removal of puctuations for sentiment analysis
        lemma=True
    )
)

final_df

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/szonjapike/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
100%|██████████| 6439/6439 [25:53<00:00,  4.15it/s]
/var/folders/j9/xwn5j6q56m7582c0z7xr8wh80000gn/T/ipykernel_1374/3376571520.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['speeches_for_keyword_search'] = final_df['Speech'].progress_apply(

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens,Income Level,speeches_for_keyword_search
0,45,1990,NZL,"﻿\nI should like to congratulate you, Sir, on ...",145,3512,4,i should like to congratulate you sir on your ...
1,45,1990,EGY,"﻿First of all, I would like to extend may dele...",76,2532,1,first of all i would like to extend may delega...
3,45,1990,CPV,﻿I should like to begin by offering Mr. de Mar...,71,2432,2,i should like to begin by offering mr. de marc...
4,45,1990,UGA,"﻿In 1967, I had the privilege of addressing th...",132,3508,1,in 1967 i have the privilege of address this a...
5,45,1990,NLD,"﻿\nMay I, first of all, extend to Mr. de Marco...",167,4134,4,may i first of all extend to mr. de marco my c...
...,...,...,...,...,...,...,...,...
6517,79,2024,CIV,Mr President of the 79th Session of the United...,41,1206,2,lady and gentleman head of state and governmen...
6518,79,2024,HND,"Madam President of this General Assembly, \nM...",54,1367,2,madam president of this general assembly mr. s...
6519,79,2024,MKD,Distinguished President of the United Nations ...,101,2804,3,lady and gentleman be invite to address this 7...
6520,79,2024,KOR,"Mr. President,\nMr. Secretary-General,\nDistin...",31,821,4,mr. president mr. secretary-general distinguis...
6521,79,2024,SGP,"Mdm President, Your Excellencies \n \n \n1 I...",100,2208,4,excellency 1 i bring you greeting from a tiny ...

# Step 3: Look for the keywords

In [27]:
# Climate keyword according to the literature
climate_keywords = ["climate change", "global warming", "cap and trade", "unfccc", "paris accord", "emissions trading scheme", "global average temperature",
            "kyoto protocol", "climate resilience", "carbon dioxide", "climate politics", "framework convention on climate change", "ball roadmap", "greenhouse gas", "ghg",
            "greenhouse effect", "ipcc", "climate mitigation", "climate action", "emissions"]

In [28]:
def extract_keyword_info(text, keywords):
    """
    Extracts climate-related keyword information from a text string.

    Parameters:
        text (str): The speech or text in which to search for keywords.
        keywords (list of str): A list of climate-related keywords or phrases to match against the text.
    """
    matches = []
    for kw in keywords:
        pattern = r'\b' + re.escape(kw) + r'\b'
        if re.search(pattern, text):
            matches.append(kw)
    contains_keyword = len(matches) > 0
    return pd.Series([matches, contains_keyword])

In [29]:
final_df[['matched_climate_keywords', 'contains_climate_keyword']] = final_df['speeches_for_keyword_search'].apply(
    lambda text: extract_keyword_info(text, climate_keywords)
)

final_df

/var/folders/j9/xwn5j6q56m7582c0z7xr8wh80000gn/T/ipykernel_1374/2518621349.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[['matched_climate_keywords', 'contains_climate_keyword']] = final_df['speeches_for_keyword_search'].apply(
/var/folders/j9/xwn5j6q56m7582c0z7xr8wh80000gn/T/ipykernel_1374/2518621349.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[['matched_climate_keywords', 'contains_climate_keyword']] = final_df['speeches_for_keyword_search'].apply(

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens,Income Level,speeches_for_keyword_search,matched_climate_keywords,contains_climate_keyword
0,45,1990,NZL,"﻿\nI should like to congratulate you, Sir, on ...",145,3512,4,i should like to congratulate you sir on your ...,"[climate change, greenhouse gas]",True
1,45,1990,EGY,"﻿First of all, I would like to extend may dele...",76,2532,1,first of all i would like to extend may delega...,[],False
3,45,1990,CPV,﻿I should like to begin by offering Mr. de Mar...,71,2432,2,i should like to begin by offering mr. de marc...,[],False
4,45,1990,UGA,"﻿In 1967, I had the privilege of addressing th...",132,3508,1,in 1967 i have the privilege of address this a...,[],False
5,45,1990,NLD,"﻿\nMay I, first of all, extend to Mr. de Marco...",167,4134,4,may i first of all extend to mr. de marco my c...,[],False
...,...,...,...,...,...,...,...,...,...,...
6517,79,2024,CIV,Mr President of the 79th Session of the United...,41,1206,2,lady and gentleman head of state and governmen...,"[climate change, climate action]",True
6518,79,2024,HND,"Madam President of this General Assembly, \nM...",54,1367,2,madam president of this general assembly mr. s...,[],False
6519,79,2024,MKD,Distinguished President of the United Nations ...,101,2804,3,lady and gentleman be invite to address this 7...,"[climate change, greenhouse gas, climate action]",True
6520,79,2024,KOR,"Mr. President,\nMr. Secretary-General,\nDistin...",31,821,4,mr. president mr. secretary-general distinguis...,[],False
6521,79,2024,SGP,"Mdm President, Your Excellencies \n \n \n1 I...",100,2208,4,excellency 1 i bring you greeting from a tiny ...,[climate change],True

In [32]:
df_sentiment = final_df[final_df['contains_climate_keyword']]
df_sentiment

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens,Income Level,speeches_for_keyword_search,matched_climate_keywords,contains_climate_keyword
0,45,1990,NZL,"﻿\nI should like to congratulate you, Sir, on ...",145,3512,4,i should like to congratulate you sir on your ...,"[climate change, greenhouse gas]",True
13,45,1990,ITA,"﻿Sir, on taking the floor on behalf of the Eur...",151,4568,4,sir on take the floor on behalf of the europea...,[climate change],True
20,45,1990,PNG,﻿On behalf of the Government and people\nof Pa...,113,2923,2,on behalf of the government and people of papu...,"[greenhouse gas, greenhouse effect]",True
24,45,1990,FIN,"﻿\nI take great pleasure in seeing you, Sir, a...",92,2080,4,i take great pleasure in see you sir a disting...,[carbon dioxide],True
29,45,1990,DEU,"﻿I wish first of all to offer you, Mr. Preside...",292,6149,4,mr. president my warm congratulation on your e...,"[carbon dioxide, greenhouse effect]",True
...,...,...,...,...,...,...,...,...,...,...
6514,79,2024,CHE,Mr President\nSecretary-General\nExcellencies\...,66,1314,4,lady and gentleman on the morning of 3 march 2...,[climate change],True
6515,79,2024,CUB,"**Mr President,** \n**Mr Secretary-General,**...",76,2433,3,mr president * * * * mr secretary-general * * ...,"[climate change, global average temperature]",True
6517,79,2024,CIV,Mr President of the 79th Session of the United...,41,1206,2,lady and gentleman head of state and governmen...,"[climate change, climate action]",True
6519,79,2024,MKD,Distinguished President of the United Nations ...,101,2804,3,lady and gentleman be invite to address this 7...,"[climate change, greenhouse gas, climate action]",True
6521,79,2024,SGP,"Mdm President, Your Excellencies \n \n \n1 I...",100,2208,4,excellency 1 i bring you greeting from a tiny ...,[climate change],True

In [27]:
#final_df.to_csv(dataset_path + "df_speeches_for_keywords.csv", index=False, encoding='utf-8')

In [42]:
# Now get the sentences that have the keywords in them and add them to a list in a column
from nltk.tokenize import sent_tokenize

nltk.download('punkt')

def extract_climate_sentences(speech, keywords):
    sentences = sent_tokenize(speech)
    keyword_sentences = []
    for sent in sentences:

        # Check if any keyword appears in the sentence (case-insensitive)
        if any(kw.lower() in sent.lower() for kw in keywords):
            keyword_sentences.append(sent.strip())
    return keyword_sentences

df_sentiment['climate_sentences'] = df_sentiment.apply(
    lambda row: extract_climate_sentences(row['speeches_for_keyword_search'], row['matched_climate_keywords']),
    axis=1
)

df_sentiment
# Optional: drop rows with no matching climate sentences (e.g., just to be safe)
#df = [df['climate_sentences'].map(len) > 0]

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/szonjapike/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
/var/folders/j9/xwn5j6q56m7582c0z7xr8wh80000gn/T/ipykernel_1374/1212155310.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sentiment['climate_sentences'] = df_sentiment.apply(

,Session,Year,ISO-Code,Speech,number_sentences,number_tokens,Income Level,speeches_for_keyword_search,matched_climate_keywords,contains_climate_keyword,climate_sentences
0,45,1990,NZL,"﻿\nI should like to congratulate you, Sir, on ...",145,3512,4,i should like to congratulate you sir on your ...,"[climate change, greenhouse gas]",True,[but many of those be small island atoll count...
13,45,1990,ITA,"﻿Sir, on taking the floor on behalf of the Eur...",151,4568,4,sir on take the floor on behalf of the europea...,[climate change],True,[perhaps never in the post-war period have the...
20,45,1990,PNG,﻿On behalf of the Government and people\nof Pa...,113,2923,2,on behalf of the government and people of papu...,"[greenhouse gas, greenhouse effect]",True,[we be greatly concerned that in spite of omin...
24,45,1990,FIN,"﻿\nI take great pleasure in seeing you, Sir, a...",92,2080,4,i take great pleasure in see you sir a disting...,[carbon dioxide],True,[i be think for example of policy to reduce em...
29,45,1990,DEU,"﻿I wish first of all to offer you, Mr. Preside...",292,6149,4,mr. president my warm congratulation on your e...,"[carbon dioxide, greenhouse effect]",True,[another key problem be the change of the worl...
...,...,...,...,...,...,...,...,...,...,...,...
6514,79,2024,CHE,Mr President\nSecretary-General\nExcellencies\...,66,1314,4,lady and gentleman on the morning of 3 march 2...,[climate change],True,[climate change and loss of biodiversity be ha...
6515,79,2024,CUB,"**Mr President,** \n**Mr Secretary-General,**...",76,2433,3,mr president * * * * mr secretary-general * * ...,"[climate change, global average temperature]",True,"[* * climate change be advance inexorably ., u..."
6517,79,2024,CIV,Mr President of the 79th Session of the United...,41,1206,2,lady and gentleman head of state and governmen...,"[climate change, climate action]",True,[* * mr president * * the progress achieve by ...
6519,79,2024,MKD,Distinguished President of the United Nations ...,101,2804,3,lady and gentleman be invite to address this 7...,"[climate change, greenhouse gas, climate action]",True,[6. with the alarm level of greenhouse gas emi...
6521,79,2024,SGP,"Mdm President, Your Excellencies \n \n \n1 I...",100,2208,4,excellency 1 i bring you greeting from a tiny ...,[climate change],True,[on almost every issue confront the world – fr...

In [44]:
df_sentiment.to_csv(dataset_path + "df_sentiment_analysis.csv", index=False, encoding='utf-8')

In [41]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment import SentimentIntensityAnalyzer

sentence = 'this be among the most important action that a country can take in directly tackle climate change and reaffirm it commitment to the paris agreement .'
sia = SentimentIntensityAnalyzer()
sentiment = sia.polarity_scores(sentence)
print(sentiment)

{'neg': 0.0, 'neu': 0.727, 'pos': 0.273, 'compound': 0.7841}

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/szonjapike/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!